# Generated by Django 5.1.5 on 2025-01-31 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_behavior_reward_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='did_not_finish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='finished_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='fun_rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Sucked'), (2, 'Okay'), (3, 'Dont Care'), (4, 'Fun'), (5, 'Super Fun')], null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='not_quite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='time_taken',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Right Now')], default=2),
        ),
    ]
